dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install typings --global
  - typings install dt~jasmine --save --global
  - npm install -g requirejs
  - npm install -g jasmine
  - npm install -g jasmine-core
  - npm install -g karma
  - npm install -g karma-requirejs
  - npm install -g karma-jasmine
  - npm install -g karma-firefox-launcher
  - npm install
script:
  - npm run test-once
